
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycczzqvixbfqakkjnset.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljY3p6cXZpeGJmcWFra2puc2V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3NTcwMjUsImV4cCI6MjA1NjMzMzAyNX0.lc_x5A5qkF-LWQItj44cO4uTWiWa7Y8YLetiIyTSjrw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
