// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggsmginwnfdvhnuqashe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdnc21naW53bmZkdmhudXFhc2hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3ODg3ODEsImV4cCI6MjA1NjM2NDc4MX0.ThmYE6uRPWID3eVhaZu84NBO7HLhzYjCgkctQYmqJH8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);